import Head from 'next/head';
import MasterLayout from '../../components/templates/MaterLayout';
import { LoginScreen } from '../../components/organisms/loginScreen'

const SignIn = () => {
    return (
        <>
            <Head>
            <title>Nación eSports | Tienda</title>
            <meta name="description" content="Generated by create next app" />
            <meta property="og:description" content="¿Quieres ser jugador E-Sports? Registrate en la plataforma, es gratis y en pocos pasos" />
            <meta property="og:title" content="Nacion E-Sports | Atrevete a unirte al mundo de E-Sports" />
            <meta property="og:image" content="/images/01.png" />
            <link rel="icon" href="/images/01.png" />
            </Head>
            <div>
                <LoginScreen />
            </div>
        </>
    )
}
SignIn.Layout = MasterLayout;
export default SignIn;
