export const drawerConfig = [
  {
    title: 'Inicio',
    // icon: HomeLogo,
    url: '/',
    requireAuth: false,
    id: 'home',
  },
  // {
  //   render: MenuCategories,
  //   requireAuth: false,
  // },
  {
    title: 'Ligas',
    // icon: ReferralsLogo,
    url: '/leagues',
    requireAuth: false,
    id: 'league',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'TORNEOS E-SPORT',
    // icon: ReferralsLogo,
    url: '/leagues',
    requireAuth: false,
    id: 'league',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Torneos Comunidad',
    // icon: OrdersLogo,
    url: '/tournaments-home',
    requireAuth: false,
    id: 'tournamentEsport',
  },
  {
    title: 'Logo',
    // icon: OrdersLogo,
    url: '/',
    requireAuth: false,
    id: 'logo',
  },
  {
    title: 'Academia',
    // icon: ReferralsLogo,
    url: '/academia',
    requireAuth: false,
    id: 'academia',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Streaming',
    // icon: ReferralsLogo,
    url: '/streaming',
    requireAuth: false,
    id: 'streaming',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Tienda',
    // icon: ReferralsLogo,
    url: '/store',
    requireAuth: false,
    id: 'shop',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Noticias',
    // icon: ReferralsLogo,
    url: '/news',
    requireAuth: false,
    id: 'notices',
    // hidden: referralsAllowed !== 'allowed',
  },
];

export const drawerConfig2 = [
  {
    title: 'Inicio',
    // icon: HomeLogo,
    url: '/',
    requireAuth: false,
    id: 'home',
  },
  // {
  //   render: MenuCategories,
  //   requireAuth: false,
  // },
  {
    title: 'Ligas',
    // icon: ReferralsLogo,
    url: '/leagues',
    requireAuth: false,
    id: 'league',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'TORNEOS E-SPORT',
    // icon: ReferralsLogo,
    url: '/leagues',
    requireAuth: false,
    id: 'league',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Logo',
    // icon: OrdersLogo,
    url: '/',
    requireAuth: false,
    id: 'logo',
  },
  {
    title: 'Streaming',
    // icon: ReferralsLogo,
    url: '/streaming',
    requireAuth: false,
    id: 'streaming',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Tienda',
    // icon: ReferralsLogo,
    url: '/store',
    requireAuth: false,
    id: 'shop',
    // hidden: referralsAllowed !== 'allowed',
  },
  {
    title: 'Noticias',
    // icon: ReferralsLogo,
    url: '/news',
    requireAuth: false,
    id: 'notices',
    // hidden: referralsAllowed !== 'allowed',
  },
];

