import React from 'react'
import TagManager from 'react-gtm-module';
import Head from 'next/head';
import { Card, Col, Container, Row } from 'react-bootstrap';
import MasterLayout from '../../components/templates/MaterLayout';
import { NewHomeMolecule } from '../../components/molecules/home-new-molecule-homes';
import { Breadcrumb } from '../../components/molecules/Breadcrumb';
import { LeaguesTransmitions } from '../../components/organisms/streaming-transmitions';

const Streaming = () => {    TagManager.dataLayer({
    dataLayer:{
      event: 'page_title',
      path: `/streaming-home`
    }
  })
    return (
        <>
        <Head>
          <title>Nación eSports | Streaming</title>
          <meta name="description" content="Generated by create next app" />
          <meta property="og:description" content="¿Quieres ser jugador E-Sports? Registrate en la plataforma, es gratis y en pocos pasos" />
          <meta property="og:title" content="Nacion E-Sports | Atrevete a unirte al mundo de E-Sports" />
          <meta property="og:image" content="http://localhost:3000/fine.png" />
          <link rel="icon" href="/images/01.png" />
        </Head>
        <div>
            <NewHomeMolecule 
                img={'https://nacionbe-sports-images.s3.amazonaws.com/b10df846-0441-4da2-85dc-427987aa0344.png'}
                leftTitle={''}
                leftDescrition={''}
            />
            <Breadcrumb text='Streaming' type={2} />
            <LeaguesTransmitions />
        </div>
    </>
    )
}

Streaming.Layout = MasterLayout;
export default Streaming
